version: '3.3'
services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    container_name: postgresql
    entrypoint:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_manager

  book-manager:
    build: BookManager
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    container_name: book-manager
